### ISSUE TITLE
put-value

### ISSUE THREAD

**Issue by doowb** [doowb/upsert-value#1]
Waiting on [this issue](https://github.com/tunnckoCore/put-value/issues/1) to publish to npm.

**Comment by tunnckoCore** [comment]
i think it would be better to use `has-own-deep`, 2c
cuz falsey values are possible use case and when we use just `has-value` it will fail on them, that was one point for what im starting all that.

**Comment by doowb** [comment]
Good call.

**Comment by tunnckoCore** [comment]
@jonschlinkert same applies for `set-value`
